<%@ page import="Dao.User" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Flower Booking System Homepage</title>
  <link rel="stylesheet" href="css/public.css">
  <style>
    .box {
      width: 600px;
      height: 600px;
      display: flex;
      justify-content: center;
      align-items: center;
      background-image: url('1.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }

    .box button {
      width: 50px;
      height: 50px;
    }
  </style>
</head>

<body style="background-color: lightblue;">
<jsp:useBean id="user" scope="session" class="Dao.User"></jsp:useBean>

<div id="head">
  <!-- logo-->
  <div id="head_left">
    <a href="index.jsp"></a>
  </div>
  <div id="head_top">
    <%
      Object userObj = session.getAttribute("user");
      if (userObj!= null && userObj instanceof User && ((User) userObj).getUsername()!= null) {
    %>
    <a href="UserExitServlet"><span>[Logout]</span></a>
    <span>Welcome: <%= ((User) userObj).getUsername() %></span>
    <%
    } else {
    %>
    <a href="register.jsp"><span>[Register]</span></a>
    <a href="login.jsp"><span>[Login]</span></a>
    <%
      }
    %>
  </div>
  <!-- nav-->
  <div id="head_right">
    <ul>
      <li><a href="index.jsp">Homepage</a></li>
      <li><a href="MemberServlet">Member Management Center</a></li>
    </ul>
  </div>
</div>

<div class="box">
  <button type="button" onclick="window.location.href='login.jsp'"> go</button>
</div>

<div id="body">
  <h2>Welcome to the Flower Booking System</h2>
  <p>This is the world of flowers, providing you with various beautiful flowers.</p>
  <c:if test="${user.username!= null}">
    <p>Dear ${user.username}, wish you a happy shopping!</p>
  </c:if>
  <div id="flowerList">
    <!-- Assume that the flower list is dynamically generated by Servlet here -->
    <c:forEach var="flower" items="${flowers}">
      <div class="flowerItem">
        <img src="${flower.image}" alt="${flower.name}" width="200px" height="200px">
        <h3>${flower.name}</h3>
        <p>Price: ${flower.price}</p>
        <p>Description: ${flower.description}</p>
        <c:if test="${user.username!= null}">
          <form action="AddToCartServlet" method="post">
            <input type="hidden" name="flowerId" value="${flower.flower_id}">
            <input type="number" name="quantity" value="1" min="1">
            <input type="submit" value="Add to Cart">
          </form>
        </c:if>
      </div>
    </c:forEach>
  </div>
</div>

<div id="footer">
  <span>Flower Booking System</span>
</div>

</body>

</html>